pipeline:
  data_dir: "./VAI_NVS_DATA_ROUND2/phase1/public_set"
  output_dir: "./output"

training:
  iterations: 30000
  resolution: 2
  data_device: "cpu"
  sh_degree: 3

render:
  skip_training: false
  format: "jpg"
